spring.datasource.url=jdbc:postgresql://ep-jolly-dust-aptsdhs5-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8NTm4pzDoxqi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
