spring.datasource.url=jdbc:postgresql://localhost:5432/reactadmintd
spring.datasource.username=ferrissushi
spring.datasource.password=tellmeyourname
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
